'use client';

import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';

export function ScrollVideo() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [fireflies, setFireflies] = useState<any[]>([]);
  const [loadedPercent, setLoadedPercent] = useState(0);

  useEffect(() => {
    // Generate firefly values on client only to prevent SSR hydration mismatch
    const generated = Array.from({ length: 45 }).map((_, i) => ({
      id: i,
      x: Math.random() * 100, // percentage left
      y: Math.random() * 100, // percentage top
      size: Math.random() * 3 + 1, // 1-4px
      glow: Math.random() * 5 + 3, // 3-8px glow
    }));
    setFireflies(generated);
  }, []);

  // GSAP Animation for realistic drifting
  useEffect(() => {
    if (fireflies.length === 0) return;

    const ctx = gsap.context(() => {
      // For each firefly, create a unique, infinite drifting tween
      gsap.utils.toArray('.firefly-particle').forEach((el: any) => {
        // Slow drifting motion
        gsap.to(el, {
          x: `random(-100, 100)`,
          y: `random(-100, 100)`,
          duration: `random(5, 10)`,
          ease: "sine.inOut",
          repeat: -1,
          repeatRefresh: true, // gets new random values on each repeat
          yoyo: true,
        });

        // Pulsing glow (flicker)
        gsap.to(el, {
          opacity: `random(0.2, 1)`,
          duration: `random(1, 4)`,
          ease: "sine.inOut",
          repeat: -1,
          repeatRefresh: true,
          yoyo: true,
        });
      });
    });

    return () => ctx.revert();
  }, [fireflies]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const totalFrames = 202; // As generated by our script
    const images: HTMLImageElement[] = [];
    let loadedCount = 0;

    // 1. Preload all images into memory
    for (let i = 1; i <= totalFrames; i++) {
      const img = new Image();
      const paddedIndex = String(i).padStart(4, '0');
      img.src = `/video-frames/frame_${paddedIndex}.jpg`;
      img.onload = () => {
        loadedCount++;
        setLoadedPercent(Math.floor((loadedCount / totalFrames) * 100));
      };
      images.push(img);
    }

    let rafId: number;
    let targetIndex = 0;
    let currentIndex = 0;
    let lastDrawnFrame = -1;

    const renderLoop = () => {
      rafId = requestAnimationFrame(renderLoop);

      // 2. Calculate scroll progress
      const scrollTop = window.scrollY || document.documentElement.scrollTop;
      const docHeight = Math.max(
        document.body.scrollHeight, 
        document.documentElement.scrollHeight,
        document.body.offsetHeight
      );
      const winHeight = window.innerHeight;
      const maxScroll = docHeight - winHeight;

      if (maxScroll > 0) {
        const progress = Math.max(0, Math.min(1, scrollTop / maxScroll));
        targetIndex = progress * (totalFrames - 1);
      }

      // 3. Smooth the index
      // Since Lenis already provides buttery smooth scroll values, we use a higher lerp 
      // here (0.2) to tightly couple the video to the scroll without lag.
      currentIndex += (targetIndex - currentIndex) * 0.2;
      const frameToDraw = Math.round(currentIndex);

      // 4. Draw to canvas (only if frame changed to save GPU)
      if (frameToDraw !== lastDrawnFrame) {
        const img = images[frameToDraw];
        if (img && img.complete && img.naturalWidth > 0) {
          if (canvas.width !== img.width || canvas.height !== img.height) {
            canvas.width = img.width;
            canvas.height = img.height;
          }
          ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
          lastDrawnFrame = frameToDraw; // Update only after successful draw
        }
      }
    };

    rafId = requestAnimationFrame(renderLoop);

    return () => {
      cancelAnimationFrame(rafId);
    };
  }, []);

  return (
    <div className="fixed inset-0 w-full h-full z-0 pointer-events-none bg-void overflow-hidden">
      
      {/* Loading Cinematic Overlay */}
      <div 
        className={`absolute inset-0 flex flex-col items-center justify-center bg-void z-30 text-bone transition-opacity duration-1000 ${loadedPercent >= 100 ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}
      >
        <span className="font-quicksand text-sm uppercase tracking-[0.3em] mb-4 text-boneDim">Loading Pilgrimage</span>
        <div className="w-64 h-1 bg-voidSofter rounded-full overflow-hidden">
          <div className="h-full bg-moss transition-all duration-300" style={{ width: `${loadedPercent}%` }} />
        </div>
      </div>

      {/* Canvas rendering the video frames */}
      <canvas
        ref={canvasRef}
        className="absolute inset-0 w-full h-full object-cover"
      />

      {/* Darkening Overlay to make text pop */}
      <div className="absolute inset-0 bg-black/50 pointer-events-none z-10" />

      {/* Global Fireflies Overlay */}
      <div className="absolute inset-0 pointer-events-none z-20 overflow-hidden">
        {fireflies.map((fly) => (
          <div
            key={fly.id}
            className="firefly-particle absolute rounded-full"
            style={{
              backgroundColor: '#FFEBB3', // Pale warm amber-white core
              left: `${fly.x}%`,
              top: `${fly.y}%`,
              width: `${fly.size}px`,
              height: `${fly.size}px`,
              boxShadow: `0 0 ${fly.glow * 2}px ${fly.glow}px rgba(230, 160, 80, 0.65)`, // Dusty warm amber glow
            }}
          />
        ))}
      </div>
    </div>
  );
}
